FROM python:3.11

RUN apt update
RUN pip install flask
RUN pip install flask_cors
RUN pip install flask_sqlalchemy
RUN pip install flask_migrate
RUN pip install pymysql
RUN pip install mysql.connector
RUN pip install pytest
RUN pip install flask_swagger_ui
